/*
 * RedMailGui.java
 *
 * Created on 18.01.2013, 15:40:20
 */
package redmail;

/**
 * Gui for RedMail
 * @author alex
 */
public class RedMailGui extends javax.swing.JFrame {
    
    private RedMail redmail;
            
    /** Creates new form RedMailGui */
    public RedMailGui() {
        initComponents();
        redmail = new RedMail();
        redmail.setBrowserPanel(jLabel4);
        redmail.setLogPanel(LogTextArea);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonsPanel = new javax.swing.JPanel();
        GetLinksButton = new javax.swing.JButton();
        NextLinkButton = new javax.swing.JButton();
        ReloadLinkButton = new javax.swing.JButton();
        PrevLinkButton = new javax.swing.JButton();
        ReadLinksButton = new javax.swing.JButton();
        WriteLinksButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        BrowserPanel = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ListPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListTable = new javax.swing.JTable();
        LogPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        LogTextArea = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jMenuBar1 = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        ReadLinksMenu = new javax.swing.JMenuItem();
        WriteLinksMenu = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        ExitMenu = new javax.swing.JMenuItem();
        EditMenu = new javax.swing.JMenu();
        AutoGetMenu = new javax.swing.JCheckBoxMenuItem();
        AutoViewMenu = new javax.swing.JCheckBoxMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        SettingsMenu = new javax.swing.JMenuItem();
        HelpMenu = new javax.swing.JMenu();
        IndexMenu = new javax.swing.JMenuItem();
        StatMenu = new javax.swing.JMenuItem();
        AboutMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ButtonsPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ButtonsPanel.setFocusable(false);
        ButtonsPanel.setFont(new java.awt.Font("Droid Sans", 0, 12));
        ButtonsPanel.setLayout(new java.awt.GridLayout(6, 1, 10, 10));

        GetLinksButton.setText("Get Links");
        GetLinksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetLinksButtonActionPerformed(evt);
            }
        });
        ButtonsPanel.add(GetLinksButton);

        NextLinkButton.setText("Next");
        NextLinkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextLinkButtonActionPerformed(evt);
            }
        });
        ButtonsPanel.add(NextLinkButton);

        ReloadLinkButton.setText("Reload");
        ReloadLinkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReloadLinkButtonActionPerformed(evt);
            }
        });
        ButtonsPanel.add(ReloadLinkButton);

        PrevLinkButton.setText("Prev");
        PrevLinkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrevLinkButtonActionPerformed(evt);
            }
        });
        ButtonsPanel.add(PrevLinkButton);

        ReadLinksButton.setText("Read Links");
        ReadLinksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReadLinksButtonActionPerformed(evt);
            }
        });
        ButtonsPanel.add(ReadLinksButton);

        WriteLinksButton.setText("Write Links");
        WriteLinksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WriteLinksButtonActionPerformed(evt);
            }
        });
        ButtonsPanel.add(WriteLinksButton);

        BrowserPanel.setBackground(new java.awt.Color(122, 143, 255));

        jTextField1.setText("jTextField1");

        jLabel1.setText("jLabel1");

        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout BrowserPanelLayout = new javax.swing.GroupLayout(BrowserPanel);
        BrowserPanel.setLayout(BrowserPanelLayout);
        BrowserPanelLayout.setHorizontalGroup(
            BrowserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BrowserPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(BrowserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(BrowserPanelLayout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116)
                        .addComponent(jLabel4)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        BrowserPanelLayout.setVerticalGroup(
            BrowserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BrowserPanelLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(BrowserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BrowserPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(29, 29, 29))
                    .addGroup(BrowserPanelLayout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Browser", BrowserPanel);

        ListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(ListTable);

        javax.swing.GroupLayout ListPanelLayout = new javax.swing.GroupLayout(ListPanel);
        ListPanel.setLayout(ListPanelLayout);
        ListPanelLayout.setHorizontalGroup(
            ListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addContainerGap())
        );
        ListPanelLayout.setVerticalGroup(
            ListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("List", ListPanel);

        LogTextArea.setColumns(20);
        LogTextArea.setRows(5);
        jScrollPane2.setViewportView(LogTextArea);

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        javax.swing.GroupLayout LogPanelLayout = new javax.swing.GroupLayout(LogPanel);
        LogPanel.setLayout(LogPanelLayout);
        LogPanelLayout.setHorizontalGroup(
            LogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addGroup(LogPanelLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        LogPanelLayout.setVerticalGroup(
            LogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Log", LogPanel);

        FileMenu.setText("File");

        ReadLinksMenu.setText("Read Links");
        FileMenu.add(ReadLinksMenu);

        WriteLinksMenu.setText("Write Links");
        FileMenu.add(WriteLinksMenu);
        FileMenu.add(jSeparator2);

        ExitMenu.setText("Exit");
        FileMenu.add(ExitMenu);

        jMenuBar1.add(FileMenu);

        EditMenu.setText("Edit");

        AutoGetMenu.setSelected(true);
        AutoGetMenu.setText("Auto Get");
        EditMenu.add(AutoGetMenu);

        AutoViewMenu.setSelected(true);
        AutoViewMenu.setText("Auto View");
        EditMenu.add(AutoViewMenu);
        EditMenu.add(jSeparator1);

        SettingsMenu.setText("jMenuItem1");
        EditMenu.add(SettingsMenu);

        jMenuBar1.add(EditMenu);

        HelpMenu.setText("Help");

        IndexMenu.setText("Index");
        HelpMenu.add(IndexMenu);

        StatMenu.setText("Stat");
        HelpMenu.add(StatMenu);

        AboutMenu.setText("About");
        HelpMenu.add(AboutMenu);

        jMenuBar1.add(HelpMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButtonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void ReloadLinkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReloadLinkButtonActionPerformed
    redmail.ViewCurr();
}//GEN-LAST:event_ReloadLinkButtonActionPerformed

private void PrevLinkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrevLinkButtonActionPerformed
    redmail.ViewPrev();
}//GEN-LAST:event_PrevLinkButtonActionPerformed

private void GetLinksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetLinksButtonActionPerformed
    ListTable.setValueAt("text", 1, 0);
}//GEN-LAST:event_GetLinksButtonActionPerformed

private void NextLinkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextLinkButtonActionPerformed
    redmail.ViewNext();
}//GEN-LAST:event_NextLinkButtonActionPerformed

private void ReadLinksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadLinksButtonActionPerformed
    redmail.ReadLinksFromFile();
}//GEN-LAST:event_ReadLinksButtonActionPerformed

private void WriteLinksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WriteLinksButtonActionPerformed
    redmail.WriteLinksToFile();
}//GEN-LAST:event_WriteLinksButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RedMailGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RedMailGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RedMailGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RedMailGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new RedMailGui().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AboutMenu;
    private javax.swing.JCheckBoxMenuItem AutoGetMenu;
    private javax.swing.JCheckBoxMenuItem AutoViewMenu;
    private javax.swing.JPanel BrowserPanel;
    private javax.swing.JPanel ButtonsPanel;
    private javax.swing.JMenu EditMenu;
    private javax.swing.JMenuItem ExitMenu;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JButton GetLinksButton;
    private javax.swing.JMenu HelpMenu;
    private javax.swing.JMenuItem IndexMenu;
    private javax.swing.JPanel ListPanel;
    private javax.swing.JTable ListTable;
    private javax.swing.JPanel LogPanel;
    private javax.swing.JTextArea LogTextArea;
    private javax.swing.JButton NextLinkButton;
    private javax.swing.JButton PrevLinkButton;
    private javax.swing.JButton ReadLinksButton;
    private javax.swing.JMenuItem ReadLinksMenu;
    private javax.swing.JButton ReloadLinkButton;
    private javax.swing.JMenuItem SettingsMenu;
    private javax.swing.JMenuItem StatMenu;
    private javax.swing.JButton WriteLinksButton;
    private javax.swing.JMenuItem WriteLinksMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
